#!/bin/sh
#Script criado por Hecton P.Domingos hectonpdomingos@gmail.com
#DESCONTINUADO 2004-2006

data=$(date +%d-%m-%y)

# criando pasta e alguns arquivos de troca
mkdir /tmp/backup-$data
touch /tmp/backup.tmp
touch /tmp/redes.tmp
touch /tmp/nome.tmp
 while : ; do
  
# Menu do programa, simples e funcional.
         menu=$(
        dialog --stdout               \
               --title 'Backup-Linux'  \
               --menu 'Menu    Tools   Hecton' \
              0 0 0                   \
              1 'Backup homes' \
              2 'Backup dos arquivos do sitema'  \
              3 'Backup MBR'     \
              4 'Backup-Apache-MYSQL-'        \
              5 'Clonar HD com dd' \
              6 'Gravar Backup em...'  \
              7 'rsync' \
	      8 'Instalar Programas' \
	      9 'Redirecionar portas' \
             10 'Bk-hbackup' \
             11 'compartilhar conexão' \
	     12 'Utilitarios' \
	      0 'Sair' )
         
      [ $? -ne 0 ] && break
 
# Disparo do menu, sem complicacao, 
      case "$menu" in

           1) ./hbackup-home.sh ;;
           
	   2) ./hbackup-sys.sh ;;
	   
	   3) ./hbackup-mbr.sh ;;
	              
           4) dialog                                            \
              --title 'Backup MySQL e Apache' \
              --msgbox '\nVou criar o backup dos dados do Apache e MySQL 
	       os dados do apache se encontram em /var/www e do MySQL 
	       em /var/lib/mysql, sera feita a copia para pasta temporarian  em /tmp 
	       assim que terminar o processo, indique o diretorio.' \
              40 60 ;   \
cd /tmp/backup-$data ;tar -cvzf Backup-mysql.tar.gz /var/lib/mysql ; \
               cd /tmp/backup-$data ; tar -cvzf Backup-Apache.tar.gz /var/www/ ;
               echo -e "\a" ; sleep 1 ; echo -e "\a" ; sleep 1 ;
               dialog --infobox "Concluido o backup" 10 60 ; sleep 2 ;
               echo -e "\a" ;;

             5) ./hbackup-clone.sh ;;
             6) ./hbackup-get.sh ;;
             7) dialog --inputbox "Informe a origem dos dados" 10 60  \
               "~/"  2> /tmp/origem.tmp ; orig=`cat '/tmp/origem.tmp'` ;
                dialog --inputbox "Informe o dirtorio de destino" 10 60  \
               "/dev/hdc"  2> /tmp/destino.tmp ; \
                dest=`cat '/tmp/destino.tmp'` ;  \
             rsync -Cravzp $orig $dest/ ;
           dialog --infobox 'Feito o sincronismo para sua pasta destino' 5 40 ; sleep 2 ;;

	     9)  dialog --inputbox "Interface" 10 60  \
               "eth0"  2> /tmp/interface.tmp ; inter=`cat '/tmp/interface.tmp'` ;
                dialog --inputbox "Qual a porta a ser escutada?" 10 60  \
               "80"  2> /tmp/port.tmp ; \
              port=`cat '/tmp/port.tmp'` ;  \
           dialog --inputbox "Qual a porta a ser redirecionada?" 10 60  \
               "3128"  2> /tmp/redirec.tmp ; \
redirec=`cat '/tmp/redirec.tmp'` ;  \

iptables -t nat -A  PREROUTING -i $inter -p tcp --dport $port -j REDIRECT --to-port $redirec ; \
echo -e "\a" ; sleep 1 ; echo -e "\a" ; sleep 1 ;;
             10) ./hbackup-project.sh ;;
             11)dialog --inputbox "Qual placa de rede esta a internet?" 10 60  \
               "eth0"  2> /tmp/placa.tmp ; placa=`cat '/tmp/placa.tmp'` ;
           modprobe iptables_nat
           echo 1 > /proc/sys/net/ipv4/ip-forward
           iptables -t nat -A PROSTROUTING -o $placa -j MASQUERADE ;
          echo "compartilhada a $placa com as outras" ;
echo -e "\a" ; sleep 1 ; echo -e "\a" ; sleep 1 ;;
             12) ./hbackup-util.sh ;;

             0) break ;;
      esac
done

